#!/bin/bash

formatted_date=$(date +"%Y-%m-%d %H:%M:%S")

hostname=$(hostname)

local_ip=$(toolbox local_ip)

message=$(echo  "*$hostname* *$local_ip* 🔵%0A\`$formatted_date\` %0A$@")

token=$TELEGRAM_BOT_TOKEN

curl -X POST \
  "https://api.telegram.org/bot$token/sendMessage" \
  -d chat_id=-1001382816694 \
  -d parse_mode="Markdown" \
  -d text="$message"
