[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "toolbox"
version = "0.2.3"
description = "A collection of utility functions for machine and git info"
requires-python = ">=3.8"
dependencies = [
    "python-telegram-handler @ git+https://github.com/matevosashot/python-telegram-handler.git",
    "python-telegram-bot>=21",
    "requests",
    "psutil",
]

[project.scripts]
toolbox = "toolbox._cli:main"

[tool.setuptools]
script-files = ["toolbox/pingservers", "toolbox/telesend", "toolbox/telesend-data", "toolbox/notify", "toolbox/actenv"]

[tool.setuptools.packages.find]
include = ["toolbox*"]
